name: Deploy Eleventy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect path prefix (custom domain vs project pages)
        run: |
          if [ -f CNAME ]; then
            echo "ELEVENTY_PATH_PREFIX=/" >> $GITHUB_ENV
            echo "Using custom domain; setting path prefix to /"
          else
            echo "ELEVENTY_PATH_PREFIX=/${{ github.event.repository.name }}/" >> $GITHUB_ENV
            echo "Using project pages; setting path prefix to /${{ github.event.repository.name }}/"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build
        run: npm run build

      - name: Copy CNAME into publish dir (if present)
        if: ${{ hashFiles('CNAME') != '' }}
        run: cp CNAME _site/CNAME

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          force_orphan: true

